### PR TITLE
Add support for php7

### PR DESCRIPTION
**Pull request by prisis**

### CODE REVIEW

**Comment by prisis** [comment]
I add hhvm support on a new branch

**Comment by jpcercal** [comment]
Hey @prisis  the PHPUnit tests of the PHP (7.0) are not passing.

**Comment by prisis** [comment]
hey @jpcercal, i know, didn't have enough time to fix it -.-

**Comment by jpcercal** [comment]
Well, i wrote this fix and merge your contribution, this features are already available in the release v0.1.2 (c835229).

**Comment by prisis** [comment]
@jpcercal Thanks!!

**Pull request merged**
